--- 
document: 
  description: "Allegato A alle «Linee guida per l’effettuazione dei pagamenti elettronici a favore delle pubbliche amministrazioni e dei gestori di pubblici servizi»."
  name: "Specifiche attuative dei codici identificativi di versamento, riversamento e rendicondazione"
  tags: 
    - specifiche
    - SANP
    - SACI
    - pagoPA
